"""Render what a reviewer reads.

The PR body and the refusal message are the deliverables, not byproducts. A
judge spends four minutes on this project and most of it inside one of these
two documents. If they read like a competent engineer explaining their
reasoning, the project has already succeeded.

Two phrasing commitments, both about not overclaiming:

Impact lists are stated as a floor when coverage is incomplete. Warden can
prove a consumer exists; it cannot prove it has found them all.

Fix counts distinguish what was repaired from what was merely identified. Of
eight broken consumers, four may live in this repository and four elsewhere —
saying "fixed 8" would be false.
"""

from warden.agent.models import (
    BreakageTier,
    Decision,
    Remediation,
    Verdict,
    VerificationResult,
)

_TIER_ICON = {
    BreakageTier.BREAKS: "🔴",
    BreakageTier.DEGRADES: "🟡",
    BreakageTier.TOUCHES: "⚪",
    BreakageTier.SAFE: "🟢",
}


def render_pr_body(
    verdict: Verdict,
    remediation: Remediation,
    verification: VerificationResult,
    decision: Decision,
) -> str:
    change = verdict.change
    fixed = {e.path.rsplit("/", 1)[-1].removesuffix(".sql") for e in remediation.edits}

    lines = [
        f"## Warden: {change.kind.value.replace('_', ' ')} on `{change.model}"
        f"{'.' + change.column if change.column else ''}`",
        "",
        _completeness_sentence(verdict),
    ]

    if verdict.ceiling.overridden:
        lines += [
            "",
            f"> **Coverage gate overridden.** Warden would not normally generate code "
            f"at coverage {verdict.ceiling.report.score} (threshold "
            f"{verdict.ceiling.threshold_used}). Proceeding was requested with the "
            f"reason: _{verdict.ceiling.override_reason}_. Treat the impact list below "
            f"as incomplete.",
        ]

    lines += [
        "",
        "### What this change affects",
        "",
        "| | Asset | Consequence | Fixed here |",
        "|---|---|---|---|",
    ]

    for asset in verdict.impacted:
        repaired = "yes" if asset.entity.name in fixed else "no — different system"
        lines.append(
            f"| {_TIER_ICON[asset.tier]} | `{asset.entity.platform}:{asset.entity.name}` "
            f"| {asset.tier.value} | {repaired} |"
        )

    lines += ["", "### Why this fix", "", remediation.rationale]

    if remediation.alternatives:
        alternatives = ", ".join(f"`{a.value}`" for a in remediation.alternatives)
        lines += [
            "",
            f"Also valid: {alternatives}. These differ in their trade-offs, not in "
            f"correctness — the recommendation above assumes an atomic change is "
            f"acceptable.",
        ]

    if remediation.escalation:
        lines += ["", "### Needs a human decision", "", remediation.escalation]

    lines += ["", "### Verification", "", _verification_section(verification)]
    lines += ["", "### What Warden could see", "", _coverage_section(verdict)]
    lines += [
        "",
        "---",
        f"Generated by Warden. Coverage {verdict.ceiling.report.score} against a "
        f"threshold of {verdict.ceiling.threshold_used}.",
    ]

    return "\n".join(lines)


def _completeness_sentence(verdict: Verdict) -> str:
    """Impact lists are a floor, not a census, whenever the graph is dark.

    Warden gates *safety* claims on coverage but not *completeness* claims —
    it can prove a consumer exists without proving it found them all. Saying
    so is the difference between a useful list and a misleading one.
    """
    count = len(verdict.impacted)
    blocking = verdict.ceiling.blocking_spots

    if not blocking:
        return (
            f"Warden found **{count} affected asset(s)**. Lineage coverage is complete "
            f"for this subgraph, so this list is exhaustive."
        )

    platforms = sorted({s.affected_platform for s in blocking if s.affected_platform})
    dark = ", ".join(f"`{p}`" for p in platforms) or "some platforms"
    verb = "have" if len(platforms) != 1 else "has"
    return (
        f"Warden found **at least {count} affected asset(s)**. This is a floor, not a "
        f"census: {dark} {verb} no lineage connector, so consumers there cannot be "
        f"detected."
    )


def _verification_section(verification: VerificationResult) -> str:
    if not verification.attempts:
        return "_No code was executed in this run._"

    lines = []
    for attempt in verification.attempts:
        status = "passed" if attempt.passed else "failed"
        lines.append(f"- Attempt {attempt.attempt}: `{attempt.command}` — {status}")

    lines.append("")
    if verification.passed:
        lines.append(
            "The generated changes were executed before this PR was opened. They compile and run."
        )
    else:
        lines.append(
            "**Execution did not pass.** These changes are recorded for review but "
            "were not verified."
        )
    return "\n".join(lines)


def _coverage_section(verdict: Verdict) -> str:
    report = verdict.ceiling.report
    lines = [
        f"- Reached **{report.reachable_nodes}** entities out of "
        f"**{report.expected_nodes}** declared in the estate",
        f"- **{report.parsed_edge_ratio:.0%}** of lineage edges were parsed by a "
        f"connector rather than inferred",
    ]

    blocking = [s for s in report.blind_spots if s.blocks_generation]
    noted = [s for s in report.blind_spots if not s.blocks_generation]

    if blocking:
        lines += ["", "**Blind spots that could hide consumers:**"]
        lines += [f"- {s.description}" for s in blocking]
    else:
        lines.append("- No consumer-hiding blind spots in this subgraph")

    if noted:
        lines += ["", "**Noted, but cannot hide breakage from this change:**"]
        lines += [f"- {s.description}" for s in noted]

    return "\n".join(lines)


def render_refusal(verdict: Verdict, remediation: Remediation, decision: Decision) -> str:
    """The refusal message.

    A refusal that reads as evasive is worse than no tool. This one has to
    read as helpful: what was asked, what was found, precisely what is
    missing, and what would unblock it. The last part is what turns a refusal
    into a work item.
    """
    change = verdict.change
    report = verdict.ceiling.report

    lines = [
        f"## Warden held this decision — `{change.model}"
        f"{'.' + change.column if change.column else ''}`",
        "",
        "**No pull request was opened.** Warden can see part of what this change "
        "affects, but not enough to write a fix that would be complete. A partial fix "
        "presented as a whole one is worse than no fix, because the PR carries an "
        "implicit claim that it handled everything.",
        "",
        "### What is missing",
        "",
    ]

    lines += [f"- {s.description}" for s in verdict.ceiling.blocking_spots]

    lines += [
        "",
        "### What would unblock this",
        "",
        f"Ingest lineage for the platform(s) above. Warden has recorded this decision "
        f"in DataHub as blocked on **{decision.blocked_on}**; when that metadata "
        f"arrives, the analysis resumes and this PR gets opened.",
        "",
        "If your team knows the missing platform has no consumers of this change, "
        'proceed explicitly with `--override "reason"`. The reason is recorded in '
        "the resulting PR — the gate exists to prevent an accidental partial fix, not "
        "to be the final authority.",
        "",
        "### What Warden did find",
        "",
    ]

    if verdict.impacted:
        lines += [
            f"- {_TIER_ICON[a.tier]} `{a.entity.platform}:{a.entity.name}` — {a.tier.value}"
            for a in verdict.impacted
        ]
        lines += ["", "These are real, but they are a floor rather than a full list."]
    else:
        lines.append(
            "Nothing — which is not the same as nothing existing. An empty result "
            "from an incomplete graph is not evidence of absence."
        )

    lines += [
        "",
        "---",
        f"Coverage {report.score} against a threshold of "
        f"{verdict.ceiling.threshold_used}. "
        f"Query held decisions in DataHub by searching `warden:held-decision`.",
    ]

    return "\n".join(lines)
